FROM grokloc/grokloc-server:base
RUN pacman --noconfirm -S go curl gcc
ARG go_bin="/root/go/bin"
RUN mkdir -p ${go_bin}
ENV PATH="${go_bin}:${PATH}"
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ${go_bin} v1.45.2
RUN go install honnef.co/go/tools/cmd/staticcheck@latest
RUN mkdir /grokloc
WORKDIR /grokloc
CMD ["tail", "-f", "/dev/null"]

