name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -v ./...

    - name: Checks
      run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./... && go vet ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.43.0
